name: build-and-check
on:
  push:
    branches: [ main, File-Viewer-App ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build app
        run: npm run build
      - name: Lint markers & compute SHA256
        run: |
          node -e "
          const fs=require('fs');
          const t=fs.readFileSync('dist/app.html','utf8');
          const markers={
            CSP_blob: t.includes('Content-Security-Policy') && t.includes('blob:'),
            WorkerCode: t.includes('parserWorkerCode'),
            WorkerFallback: t.includes('parseInMainThread'),
            ClipboardPrompt: t.includes('Klistra in innehåll') || t.includes('prompt('),
            MenuButton: t.includes('id=\"btnMenu\"') || t.includes('id=btnMenu'),
            Snapshots_IDB: t.includes('dv_snapshots_v22') || t.includes('indexedDB.open'),
            UndoRedo: t.includes('MAX_HISTORY') || t.includes('Undo/Redo'),
            Mindmap: t.includes('canvas id=\"mind\"') || t.includes(\"getContext('2d')\"),
            TableView: t.includes('#tableHost') || t.includes('view-table')
          };
          const bad=Object.entries(markers).filter(([k,v])=>!v);
          if(bad.length){ console.error('Missing markers:', bad.map(([k])=>k).join(',')); process.exit(1); }
          console.log('Markers OK');
          "
      - name: Zip dist
        run: cd dist && zip -r app.zip . -q
      - name: Checksums
        run: |
          cd dist && (shasum -a 256 app.html README.md CHANGELOG.md QA-rapport.md app.zip || sha256sum app.html README.md CHANGELOG.md QA-rapport.md app.zip)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
