name: netlify-deploy
on:
  push:
    branches: [ main, File-Viewer-App ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure dist
        run: |
          mkdir -p dist
          [ -f dist/app.html ] || echo '<!doctype html><meta charset="utf-8"><title>stub</title>' > dist/app.html
      - name: Deploy to Netlify (prod on main, preview otherwise)
        uses: South-Paw/action-netlify-cli@v2
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          args: ${{ github.ref_name == 'main'
            && 'deploy --json --prod --dir ./dist --message "prod [''${{ github.sha }}'']" --site 66a4ee6c-ce0b-4d08-ae98-adf7c519c274'
            || 'deploy --json --dir ./dist --message "preview [''${{ github.sha }}'']" --site 66a4ee6c-ce0b-4d08-ae98-adf7c519c274' }}
